"""サイトの文言 (10 言語)。tools/build.py がこれを読んで各言語の index.html を書き出す。

- 文章の元はゲーム側のストア説明文 (burger/docs/plans/2026-08-23-store-copy.md と docs/plans/store-copy/<locale>.md)。
  用語はそこに合わせてあり、ストア説明文はゲーム内辞書 (scripts/i18n/) に合わせてある
- 値に HTML を含めてよいのは about / facts の値だけ (<strong> や <span lang>)
- ss はスクリーンショットの接頭辞 (assets/ss/<ss>-<n>.png)。ja/en は 1280x720、他は 1920x1080
"""

NBSP = " "

# 対応言語の表記 (ゲーム情報の「対応言語」に使う。表示中の言語を先頭に回す)
LANG_NAMES = [
    ("ja", "日本語"), ("en", "English"), ("zh-Hans", "简体中文"), ("zh-Hant", "繁體中文"), ("ko", "한국어"),
    ("de", "Deutsch"), ("fr", "Français"), ("es", "Español"), ("pt-BR", "Português (Brasil)"), ("ru", "Русский"),
]

# 各言語のストア名。JSON-LD の alternateName は自分以外の全部 + ローマ字表記
ALL_NAMES = ["いただきバーガー", "Itadaki Burger", "A Bun Above", "顶饱汉堡", "頂飽漢堡", "탑버거",
             "Burger obenauf", "Un pain au-dessus", "Burger a Tope", "Pão nas Alturas", "Булка Что Надо"]

LANGS = [
    # ------------------------------------------------------------------ 日本語
    dict(
        dir="", hreflang="ja", og_locale="ja_JP", steam="japanese", font="mplus",
        ss="ja", ss_size=(1280, 720), menu="日本語",
        name="いただきバーガー",
        title="いただきバーガー｜物理で積むハンバーガー・ローグライク【Steam】",
        description="「いただきバーガー」は、具材を物理で落として積み上げるハンバーガー・ローグライク。となり合う具材のシナジーで稼ぎ、崩さず高く積んでお客さんのノルマに挑む。NoZworks 開発、Steam で 2026 年発売予定。",
        og_title="いただきバーガー｜物理で積むハンバーガー・ローグライク",
        og_description="積んで、崩さず、シナジーで稼ぐ。物理で積み上げるハンバーガー・ローグライク。Steam でウィッシュリスト受付中。",
        ld_description="具材を物理で落として積み上げるハンバーガー・ローグライク。となり合う具材のシナジーで稼ぎ、崩さず高く積んでお客さんのノルマに挑む。",
        genres=["ローグライク", "デッキ構築", "物理パズル", "料理"],
        os="Windows 10 / 11 (64bit)",
        tagline="落とす！積む！挟んでシナジー！",
        subtitle="物理で積み上げるハンバーガー・ローグライク",
        cta="Steam でウィッシュリストに追加",
        release="2026年 第4四半期 発売予定 ／ Windows (Steam)",
        about_h="どんなゲーム？",
        about=[
            "<strong>いただきバーガー</strong>は、ハンバーガーを物理で積み上げるデッキ構築ローグライクです。",
            "あなたはバーガー店の店主。お客さんのノルマを満たすバーガーを、その場で組み立てて出します。"
            "ただし具材は<strong>物理で落ちる</strong>。狙って落とし、崩さず積み上げるのはあなたの腕次第。"
            "となり合った具材が次々と効果を連鎖させ、崩さず高く積むほど点が伸びます。",
        ],
        flow_h="遊びの流れ",
        steps=[
            (2, "狙って落とす", "手札の具材を皿の上に狙って落とす。具材は転がり、傾き、崩れる。どこに何を置くかで、次に乗せられるものが変わります。",
             "皿の上に具材を落として積み上げているゲーム画面"),
            (3, "挟んでシナジー", "上バンズを乗せて提供すると採点。となり合う具材の効果が連鎖して点が跳ね上がります。ノルマに届かなければ、その場でゲームオーバー。",
             "となり合う具材のシナジーで点が伸びる採点画面"),
            (5, "夜のフードトラック", "お客さんを満足させるたびにフードトラックが開店。食材箱とレリックを買い、いらない食材を処分してデッキを育て、最後のボスに挑みます。",
             "夜のフードトラックで食材箱とレリックを買うショップ画面"),
        ],
        feat_h="積み上げるもの",
        features=[
            ("具材 90種以上", "加点・倍率・受け皿。効果はすべて「となり」に向く"),
            ("レシピ 30種以上", "特定の組み合わせで全体倍率。成立すれば新しい具材が解放される"),
            ("レリック 40種以上", "タグ全体を底上げする常設効果"),
            ("店主 8人", "それぞれ専用バンズと初期デッキを持つ"),
            ("個性の違う顧客たち", "好物・苦手・骨。同じ相手でも注文は毎回変わる"),
            ("実績 70種以上", "図鑑とバーガーアルバムも収録"),
        ],
        challenge_h="腕試し",
        challenge="店の格付け★0〜5 と「熟練シェフ」(投下位置が自動で往復する) で難度を上げられます。日替わりチャレンジと延長営業のスコアは Steam ランキングで競えます。",
        shots_h="スクリーンショット",
        shots=[
            (1, "タイトル", "いただきバーガーのタイトル画面"),
            (2, "具材を落として積む", "具材を積み上げるゲーム画面"),
            (3, "シナジーで採点", "シナジーが連鎖する採点画面"),
            (4, "結果", "お客さんの結果画面"),
            (5, "夜のフードトラック", "夜のフードトラックのショップ画面"),
        ],
        info_h="ゲーム情報",
        facts=[
            ("タイトル", "いただきバーガー"),
            ("英語タイトル", '<span lang="en">A Bun Above</span>'),
            ("ジャンル", "物理積み上げ × デッキ構築ローグライク"),
            ("開発・販売", "NoZworks"),
            ("対応機種", "PC (Steam) ／ Windows 10・11 (64bit)"),
            ("発売日", "2026年 第4四半期 予定"),
            ("対応言語", None),
        ],
        cta_text="ウィッシュリストに入れて、発売を待とう",
        cta_btn="Steam ストアページへ",
        contact="お問い合わせ・取材",
        trademark="Steam は Valve Corporation の商標または登録商標です。",
        font_label="フォント",
        lang_label="言語",
    ),
    # ------------------------------------------------------------------ English
    dict(
        dir="en/", hreflang="en", og_locale="en_US", steam="english", font="mplus",
        ss="en", ss_size=(1280, 720), menu="English",
        name="A Bun Above",
        title="A Bun Above — Burger Stacking Roguelike | Steam",
        description="A Bun Above (いただきバーガー) is a physics-stacking burger roguelike. Drop ingredients onto the plate, chain synergies between neighbours and keep the tower upright to hit every customer's quota. By NoZworks, coming to Steam in 2026.",
        og_title="A Bun Above — Burger Stacking Roguelike",
        og_description="Stack it. Don't drop it. Cash in on synergy. A physics-stacking burger roguelike. Wishlist now on Steam.",
        ld_description="A physics-stacking burger roguelike where neighbouring ingredients chain effects into each other. The taller and tidier your build, the bigger the score.",
        genres=["Roguelike", "Deckbuilding", "Physics puzzle", "Cooking"],
        os="Windows 10 / 11 (64-bit)",
        tagline="Drop it! Stack it! Sandwich for synergy!",
        subtitle="A physics-stacking burger roguelike",
        cta="Wishlist on Steam",
        release="Coming Q4 2026 / Windows (Steam)",
        about_h="What is it?",
        about=[
            '<strong>A Bun Above</strong> (Japanese title: <span lang="ja">いただきバーガー</span>) is a deckbuilding roguelike where you stack burgers with real physics.',
            "You run the burger joint. Every customer names a quota, and you build the burger to meet it, live, on the plate. "
            "Trouble is, ingredients obey <strong>physics</strong>. Aiming the drop and keeping the tower upright is on you. "
            "Neighbouring ingredients chain effects into each other — the taller and tidier your build, the bigger the score.",
        ],
        flow_h="How a run goes",
        steps=[
            (2, "Aim the drop", "Drop ingredients from your hand onto the plate. They roll, tilt and topple — where you put each one decides what the next one can land on.",
             "Gameplay: dropping ingredients onto the plate to build a burger"),
            (3, "Sandwich for synergy", "Cap it with the top bun to serve and get scored. Effects chain between neighbours and the score climbs. Miss the quota and it's game over on the spot.",
             "Scoring: synergies between neighbouring ingredients stack up points"),
            (5, "The night food truck", "Clear a customer and the food truck opens: buy crates and relics, toss the stock you don't need, and grow your deck for the final boss.",
             "The night food truck shop selling crates and relics"),
        ],
        feat_h="What you stack",
        features=[
            ("90+ ingredients", "Points, multipliers, cradles. Every effect faces sideways"),
            ("30+ recipes", "Hit a combination for a whole-burger multiplier and unlock new stock"),
            ("40+ relics", "Permanent effects that lift entire tags"),
            ("8 cooks", "Each with a signature bun and starting deck"),
            ("Customers with character", "Favourites, dislikes, bones. The order shifts every time"),
            ("70+ achievements", "Plus a Codex and a Burger Album"),
        ],
        challenge_h="Prove yourself",
        challenge="Raise the stakes with shop ratings ★0–5 and Seasoned Chef, where the drop point sweeps side to side on its own. Daily challenge and Overtime scores go up on the Steam leaderboards.",
        shots_h="Screenshots",
        shots=[
            (1, "Title", "A Bun Above title screen"),
            (2, "Drop and stack", "Stacking ingredients on the plate"),
            (3, "Score the synergies", "Synergy scoring"),
            (4, "Result", "Customer result screen"),
            (5, "The night food truck", "The night food truck shop"),
        ],
        info_h="Game info",
        facts=[
            ("Title", "A Bun Above"),
            ("Japanese title", '<span lang="ja">いただきバーガー</span>'),
            ("Genre", "Physics stacking × deckbuilding roguelike"),
            ("Developer / Publisher", "NoZworks"),
            ("Platform", "PC (Steam) / Windows 10 &amp; 11 (64-bit)"),
            ("Release", "Q4 2026 (planned)"),
            ("Languages", None),
        ],
        cta_text="Wishlist it and we'll let you know at launch",
        cta_btn="Go to the Steam page",
        contact="Contact &amp; press",
        trademark="Steam is a trademark or registered trademark of Valve Corporation.",
        font_label="Fonts",
        lang_label="Language",
    ),
    # ------------------------------------------------------------------ 简体中文
    dict(
        dir="zh-hans/", hreflang="zh-Hans", og_locale="zh_CN", steam="schinese", font="sc",
        ss="zh-hans", ss_size=(1920, 1080), menu="简体中文",
        name="顶饱汉堡",
        title="顶饱汉堡｜物理堆叠的汉堡 Roguelike【Steam】",
        description="《顶饱汉堡》是一款用物理堆叠食材的汉堡 Roguelike。靠相邻食材的增益赚分，堆得又高又稳，挑战客人的目标。NoZworks 开发，预计 2026 年在 Steam 发售。",
        og_title="顶饱汉堡｜物理堆叠的汉堡 Roguelike",
        og_description="堆起来，别塌了，靠相邻增益赚分。物理堆叠的汉堡 Roguelike。现已可在 Steam 加入愿望单。",
        ld_description="物理堆叠的汉堡 Roguelike。相邻的食材会连锁触发效果，堆得越高越稳，分数越高。",
        genres=["Roguelike", "构筑", "物理益智", "料理"],
        os="Windows 10 / 11 (64位)",
        tagline="投放！堆叠！夹出增益！",
        subtitle="物理堆叠的汉堡 Roguelike",
        cta="在 Steam 加入愿望单",
        release="预计 2026 年第四季度发售 ／ Windows (Steam)",
        about_h="这是什么游戏？",
        about=[
            "<strong>顶饱汉堡</strong>是一款用物理堆叠汉堡的构筑 Roguelike。",
            "你是汉堡店的店主。当场组装出满足客人目标的汉堡上菜。"
            "但食材是<strong>按物理落下</strong>的。瞄准投放、堆稳不塌，全看你的手上功夫。"
            "相邻的食材会连锁触发效果，堆得越高越稳，分数越高。",
        ],
        flow_h="游戏流程",
        steps=[
            (2, "瞄准投放", "把手牌里的食材瞄准投到盘子上，靠相邻触发增益。食材会滚动、倾斜、倒塌，放在哪里决定了下一个能落在哪里。",
             "把食材投到盘子上堆叠的游戏画面"),
            (3, "夹出增益", "放上上层面包上菜就进入计分，相邻食材的效果连锁让分数飙升。目标未达即刻游戏结束。",
             "客人结算画面"),
            (4, "深夜餐车", "每让一位客人过关，深夜餐车（商店）就会开张。购买食材箱和遗物，丢弃不要的食材，让最后的首领满意即获胜。",
             "深夜餐车的商店画面"),
        ],
        feat_h="堆叠的内容",
        features=[
            ("食材 90种以上", "加分、倍率、接住型。所有效果都朝向「相邻」"),
            ("配方 30种以上", "特定组合触发总倍率，达成后解锁新食材"),
            ("遗物 40种以上", "提升整个标签的常驻效果"),
            ("店主 8位", "专属面包与初始构筑"),
            ("性格各异的客人", "喜爱、忌口、骨头。同一位客人每次的订单也不同"),
            ("成就 70项以上", "还收录图鉴与汉堡相册"),
        ],
        challenge_h="挑战自我",
        challenge="店铺等级★0～5与「资深主厨」（投放位置左右摆动）可以提高难度。每日挑战与延长营业的分数可在 Steam 排行榜上一较高下。",
        shots_h="游戏截图",
        shots=[
            (1, "标题画面", "顶饱汉堡的标题画面"),
            (2, "堆叠食材", "把食材堆叠在盘子上的游戏画面"),
            (3, "结算", "客人结算画面"),
            (4, "深夜餐车", "深夜餐车的商店画面"),
            (5, "图鉴", "食材图鉴画面"),
        ],
        info_h="游戏信息",
        facts=[
            ("游戏名", "顶饱汉堡"),
            ("其他名称", '<span lang="en">A Bun Above</span> ／ <span lang="ja">いただきバーガー</span>'),
            ("类型", "物理堆叠 × 构筑 Roguelike"),
            ("开发・发行", "NoZworks"),
            ("平台", "PC (Steam) ／ Windows 10・11 (64位)"),
            ("发售日", "2026年第四季度（计划）"),
            ("支持语言", None),
        ],
        cta_text="加入愿望单，等待发售",
        cta_btn="前往 Steam 商店页面",
        contact="联系・媒体采访",
        trademark="Steam 是 Valve Corporation 的商标或注册商标。",
        font_label="字体",
        lang_label="语言",
    ),
    # ------------------------------------------------------------------ 繁體中文
    dict(
        dir="zh-hant/", hreflang="zh-Hant", og_locale="zh_TW", steam="tchinese", font="tc",
        ss="zh-hant", ss_size=(1920, 1080), menu="繁體中文",
        name="頂飽漢堡",
        title="頂飽漢堡｜物理堆疊的漢堡 Roguelike【Steam】",
        description="《頂飽漢堡》是一款以物理堆疊食材的漢堡 Roguelike。靠相鄰食材的連動得分，疊得又高又穩，挑戰客人的目標分數。NoZworks 開發，預計 2026 年於 Steam 推出。",
        og_title="頂飽漢堡｜物理堆疊的漢堡 Roguelike",
        og_description="堆疊起來，別倒下，靠相鄰效應大量得分。以物理堆疊為核心的漢堡 Roguelike。現已可在 Steam 加入願望清單。",
        ld_description="以物理堆疊為核心的漢堡 Roguelike。相鄰食材會連鎖觸發效果，堆得越高越穩，分數就越高。",
        genres=["Roguelike", "套牌構築", "物理益智", "料理"],
        os="Windows 10 / 11 (64位元)",
        tagline="丟下！疊高！夾出連動！",
        subtitle="以物理堆疊為核心的漢堡 Roguelike",
        cta="在 Steam 加入願望清單",
        release="預計 2026 年第四季推出 ／ Windows (Steam)",
        about_h="這是什麼遊戲？",
        about=[
            "<strong>頂飽漢堡</strong>是一款用物理堆疊漢堡的套牌構築 Roguelike。",
            "你是漢堡店的廚師。要當場組出滿足客人目標分數的漢堡端上桌。"
            "但食材是<strong>依物理法則掉落</strong>的。瞄準投放、疊穩不塌，全靠你的手上功夫。"
            "相鄰食材會連鎖觸發效果，堆得越高越穩，分數就越高。",
        ],
        flow_h="遊戲流程",
        steps=[
            (2, "瞄準丟下", "把手牌裡的食材瞄準丟到盤子上，靠相鄰觸發連動。食材會滾動、傾斜、倒塌，放在哪裡決定了下一個能落在哪裡。",
             "把食材丟到盤子上堆疊的遊戲畫面"),
            (3, "夾出連動", "放上頂層麵包端出去就開始計分，相鄰食材的效果連鎖讓分數往上衝。目標未達立刻遊戲結束。",
             "顧客結算畫面"),
            (4, "夜間餐車", "每過一位顧客，夜間餐車（商店）就會開張。買食材箱和遺物，處理掉不需要的食材，讓最後的頭目滿意就獲勝。",
             "夜間餐車的商店畫面"),
        ],
        feat_h="疊上去的東西",
        features=[
            ("食材 90種以上", "加分、倍率、承接。所有效果都朝向「相鄰」"),
            ("配方 30種以上", "特定組合觸發全局倍率，達成後解鎖新食材"),
            ("遺物 40種以上", "提升整個標籤的常駐效果"),
            ("廚師 8位", "專屬麵包與初始套牌"),
            ("個性各異的顧客", "喜好、忌口、骨頭。同一位顧客每次點的都不一樣"),
            ("成就 70項以上", "另收錄圖鑑與漢堡相簿"),
        ],
        challenge_h="試試身手",
        challenge="店鋪等級★0～5和「資深主廚」（投放位置自動左右來回）可以拉高難度。每日挑戰與延長營業的分數能在 Steam 排行榜上一較高下。",
        shots_h="遊戲截圖",
        shots=[
            (1, "標題畫面", "頂飽漢堡的標題畫面"),
            (2, "堆疊食材", "把食材堆疊在盤子上的遊戲畫面"),
            (3, "結算", "顧客結算畫面"),
            (4, "夜間餐車", "夜間餐車的商店畫面"),
            (5, "圖鑑", "食材圖鑑畫面"),
        ],
        info_h="遊戲資訊",
        facts=[
            ("遊戲名稱", "頂飽漢堡"),
            ("其他名稱", '<span lang="en">A Bun Above</span> ／ <span lang="ja">いただきバーガー</span>'),
            ("類型", "物理堆疊 × 套牌構築 Roguelike"),
            ("開發・發行", "NoZworks"),
            ("平台", "PC (Steam) ／ Windows 10・11 (64位元)"),
            ("上市日期", "2026年第四季（預定）"),
            ("支援語言", None),
        ],
        cta_text="加入願望清單，等待上市",
        cta_btn="前往 Steam 商店頁面",
        contact="聯絡・媒體採訪",
        trademark="Steam 是 Valve Corporation 的商標或註冊商標。",
        font_label="字型",
        lang_label="語言",
    ),
    # ------------------------------------------------------------------ 한국어
    dict(
        dir="ko/", hreflang="ko", og_locale="ko_KR", steam="koreana", font="ko",
        ss="ko", ss_size=(1920, 1080), menu="한국어",
        name="탑버거",
        title="탑버거 | 물리로 쌓는 버거 로그라이크 【Steam】",
        description="「탑버거」는 재료를 물리로 떨어뜨려 쌓아 올리는 버거 로그라이크입니다. 인접한 재료의 시너지로 점수를 벌고, 무너뜨리지 않고 높이 쌓아 손님의 목표 점수에 도전하세요. NoZworks 개발, 2026년 Steam 출시 예정.",
        og_title="탑버거 | 물리로 쌓는 버거 로그라이크",
        og_description="쌓아 올리고, 무너뜨리지 말고, 인접 효과로 점수를 쓸어 담으세요. 물리 기반 쌓기 버거 로그라이크. 지금 Steam 찜 목록에 추가하세요.",
        ld_description="물리 기반 쌓기 버거 로그라이크. 서로 붙어 있는 재료가 효과를 연쇄시키고, 높고 가지런히 쌓을수록 점수가 커집니다.",
        genres=["로그라이크", "덱 빌딩", "물리 퍼즐", "요리"],
        os="Windows 10 / 11 (64비트)",
        tagline="떨어뜨리고! 쌓고! 끼워서 시너지!",
        subtitle="물리 기반 쌓기 버거 로그라이크",
        cta="Steam 찜 목록에 추가",
        release="2026년 4분기 출시 예정 ／ Windows (Steam)",
        about_h="어떤 게임인가요?",
        about=[
            "<strong>탑버거</strong>는 물리로 버거를 쌓아 올리는 덱 빌딩 로그라이크입니다.",
            "당신은 버거 가게의 요리사입니다. 손님이 부르는 목표 점수를 그 자리에서 버거로 조립해 내놓아야 합니다. "
            "문제는 재료가 <strong>물리 법칙에 따라 떨어진다</strong>는 것. 노리고 떨어뜨려서 무너지지 않게 쌓는 건 순전히 당신의 손끝에 달렸습니다. "
            "서로 붙어 있는 재료가 효과를 연쇄시키고, 높고 가지런히 쌓을수록 점수가 커집니다.",
        ],
        flow_h="게임의 흐름",
        steps=[
            (2, "노려서 떨어뜨리기", "손에 든 재료를 접시 위로 노려서 떨어뜨리고, 인접으로 시너지를 발동합니다. 재료는 구르고, 기울고, 무너집니다.",
             "접시 위에 재료를 떨어뜨려 쌓는 게임 화면"),
            (3, "끼워서 시너지", "위쪽 번을 얹어 내놓으면 채점. 인접한 재료의 효과가 연쇄하며 점수가 치솟습니다. 목표 미달이면 그 자리에서 게임 오버.",
             "손님 결과 화면"),
            (4, "밤의 푸드트럭", "손님을 한 명 처리할 때마다 밤의 푸드트럭(상점)이 열립니다. 식재료 상자와 유물을 사고 필요 없는 재료를 처분해, 마지막 보스를 만족시키면 승리입니다.",
             "밤의 푸드트럭 상점 화면"),
        ],
        feat_h="쌓아 올리는 것",
        features=[
            ("재료 90종 이상", "가점, 배율, 받아내기. 모든 효과는 \"인접\"을 향합니다"),
            ("레시피 30종 이상", "특정 조합으로 전체 배율. 성공하면 새 재료가 해금됩니다"),
            ("유물 40종 이상", "태그 전체를 끌어올리는 상시 효과"),
            ("요리사 8명", "전용 번과 초기 덱"),
            ("개성이 다른 손님들", "좋아하는 것, 싫어하는 것, 뼈. 같은 손님이라도 주문은 매번 달라집니다"),
            ("도전 과제 70개 이상", "도감과 버거 앨범도 수록"),
        ],
        challenge_h="실력 시험",
        challenge="가게 등급 ★0~5와 \"베테랑 셰프\"(투하 위치가 자동으로 좌우 왕복)로 난이도를 올릴 수 있습니다. 데일리 챌린지와 연장 영업 점수는 Steam 순위표에서 겨룹니다.",
        shots_h="스크린샷",
        shots=[
            (1, "타이틀", "탑버거 타이틀 화면"),
            (2, "재료 쌓기", "접시 위에 재료를 쌓는 게임 화면"),
            (3, "결과", "손님 결과 화면"),
            (4, "밤의 푸드트럭", "밤의 푸드트럭 상점 화면"),
            (5, "도감", "재료 도감 화면"),
        ],
        info_h="게임 정보",
        facts=[
            ("제목", "탑버거"),
            ("다른 이름", '<span lang="en">A Bun Above</span> ／ <span lang="ja">いただきバーガー</span>'),
            ("장르", "물리 쌓기 × 덱 빌딩 로그라이크"),
            ("개발・배급", "NoZworks"),
            ("플랫폼", "PC (Steam) ／ Windows 10·11 (64비트)"),
            ("출시일", "2026년 4분기 (예정)"),
            ("지원 언어", None),
        ],
        cta_text="찜 목록에 추가하고 출시를 기다려 주세요",
        cta_btn="Steam 상점 페이지로",
        contact="문의・취재",
        trademark="Steam은 Valve Corporation의 상표 또는 등록 상표입니다.",
        font_label="글꼴",
        lang_label="언어",
    ),
    # ------------------------------------------------------------------ Deutsch
    dict(
        dir="de/", hreflang="de", og_locale="de_DE", steam="german", font="mplus",
        ss="de", ss_size=(1920, 1080), menu="Deutsch",
        name="Burger obenauf",
        title="Burger obenauf – Physik-Stapel-Roguelike mit Burgern | Steam",
        description="Burger obenauf (いただきバーガー) ist ein Roguelike, in dem du Burger mit echter Physik stapelst. Lass Zutaten fallen, löse Synergien zwischen Nachbarn aus und halte den Turm stehen, um das Soll jedes Kunden zu erfüllen. Von NoZworks, erscheint 2026 auf Steam.",
        og_title="Burger obenauf – Physik-Stapel-Roguelike",
        og_description="Stapeln, nicht umwerfen, mit Synergien Kasse machen. Jetzt auf Steam auf die Wunschliste setzen.",
        ld_description="Ein Physik-Stapel-Roguelike, in dem benachbarte Zutaten Effekte aneinander weitergeben – je höher und sauberer dein Turm, desto mehr Punkte.",
        genres=["Roguelike", "Deckbuilding", "Physik-Puzzle", "Kochen"],
        os="Windows 10 / 11 (64 Bit)",
        tagline="Fallen lassen! Stapeln! Einklemmen für Synergie!",
        subtitle="Ein Physik-Stapel-Roguelike mit Burgern",
        cta="Auf Steam zur Wunschliste",
        release="Erscheint im 4. Quartal 2026 / Windows (Steam)",
        about_h="Worum geht's?",
        about=[
            "<strong>Burger obenauf</strong> ist ein Deckbuilding-Roguelike, in dem du Burger mit echter Physik stapelst.",
            "Du führst den Burgerladen. Jeder Kunde nennt ein Soll, und du baust den Burger live auf dem Teller zusammen, um es zu erfüllen. "
            "Das Problem: Zutaten gehorchen der <strong>Physik</strong>. Den Abwurf zu treffen und den Turm stehen zu halten, liegt an dir. "
            "Benachbarte Zutaten geben Effekte aneinander weiter – je höher und sauberer dein Turm, desto mehr Punkte.",
        ],
        flow_h="So läuft eine Runde",
        steps=[
            (2, "Zielen und fallen lassen", "Lass Zutaten aus der Hand gezielt auf den Teller fallen und löse Synergien zwischen Nachbarn aus. Sie rollen, kippen und stürzen um.",
             "Spielszene: Zutaten fallen auf den Teller und werden gestapelt"),
            (3, "Einklemmen für Synergie", "Setz das obere Brötchen auf und serviere – dann wird gewertet. Die Effekte der Nachbarn greifen ineinander und die Punkte steigen. Verfehlst du das Soll, ist sofort Schluss.",
             "Ergebnisbildschirm eines Kunden"),
            (4, "Der nächtliche Foodtruck", "Ist ein Kunde erledigt, öffnet der nächtliche Foodtruck (der Laden): Kisten und Relikte kaufen, überflüssige Zutaten entsorgen. Stell den letzten Boss zufrieden, und du hast gewonnen.",
             "Der nächtliche Foodtruck mit Kisten und Relikten"),
        ],
        feat_h="Was du stapelst",
        features=[
            ("Über 90 Zutaten", "Punkte, Multiplikatoren, Auffangflächen. Jeder Effekt zielt zur Seite"),
            ("Über 30 Rezepte", "Die richtige Kombination bringt einen Multiplikator auf den ganzen Burger und schaltet neue Zutaten frei"),
            ("Über 40 Relikte", "Dauerhafte Effekte, die ganze Tags anheben"),
            ("8 Köche", "Eigenes Signature-Brötchen und Startvorrat"),
            ("Kunden mit Charakter", "Lieblingszutaten, Abneigungen, Knochen. Die Bestellung ändert sich jedes Mal"),
            ("Über 70 Erfolge", "Dazu Kompendium und Burger-Album"),
        ],
        challenge_h="Beweis dich",
        challenge="Der Ladenrang ★0–5 und der Meisterkoch (der Abwurfpunkt pendelt von selbst hin und her) erhöhen den Schwierigkeitsgrad. Die Punkte der täglichen Challenge und der Überstunden landen in den Steam-Ranglisten.",
        shots_h="Screenshots",
        shots=[
            (1, "Titelbild", "Titelbildschirm von Burger obenauf"),
            (2, "Zutaten stapeln", "Zutaten auf dem Teller stapeln"),
            (3, "Ergebnis", "Ergebnisbildschirm eines Kunden"),
            (4, "Der nächtliche Foodtruck", "Der nächtliche Foodtruck (Laden)"),
            (5, "Kompendium", "Kompendium der Zutaten"),
        ],
        info_h="Spielinfos",
        facts=[
            ("Titel", "Burger obenauf"),
            ("Auch bekannt als", '<span lang="en">A Bun Above</span> / <span lang="ja">いただきバーガー</span>'),
            ("Genre", "Physik-Stapeln × Deckbuilding-Roguelike"),
            ("Entwickler / Publisher", "NoZworks"),
            ("Plattform", "PC (Steam) / Windows 10 &amp; 11 (64 Bit)"),
            ("Erscheinungstermin", "4. Quartal 2026 (geplant)"),
            ("Sprachen", None),
        ],
        cta_text="Setz es auf die Wunschliste und verpass den Release nicht",
        cta_btn="Zur Steam-Seite",
        contact="Kontakt &amp; Presse",
        trademark="Steam ist eine Marke oder eingetragene Marke der Valve Corporation.",
        font_label="Schriften",
        lang_label="Sprache",
    ),
    # ------------------------------------------------------------------ Français
    dict(
        dir="fr/", hreflang="fr", og_locale="fr_FR", steam="french", font="mplus",
        ss="fr", ss_size=(1920, 1080), menu="Français",
        name="Un pain au-dessus",
        title="Un pain au-dessus – Roguelike de burgers à empiler | Steam",
        description="Un pain au-dessus (いただきバーガー) est un roguelike où l'on empile des burgers avec une vraie physique. Lâche les ingrédients, déclenche des synergies entre voisins et garde la tour debout pour remplir le quota de chaque client. Par NoZworks, sur Steam en 2026.",
        og_title="Un pain au-dessus – Roguelike de burgers à empiler",
        og_description="Empile, ne fais rien tomber, encaisse la synergie. Ajoute-le dès maintenant à ta liste de souhaits Steam.",
        ld_description="Un roguelike de burgers à la physique réelle où les ingrédients voisins déclenchent des effets en chaîne : plus la pile est haute et nette, plus le score grimpe.",
        genres=["Roguelike", "Deckbuilding", "Puzzle physique", "Cuisine"],
        os="Windows 10 / 11 (64 bits)",
        tagline=f"Lâche-le{NBSP}! Empile-le{NBSP}! Coince-le pour la synergie{NBSP}!",
        subtitle="Un roguelike de burgers à la physique réelle",
        cta="Ajouter à ma liste de souhaits Steam",
        release="Sortie prévue au 4e trimestre 2026 / Windows (Steam)",
        about_h=f"C'est quoi{NBSP}?",
        about=[
            "<strong>Un pain au-dessus</strong> est un roguelike deckbuilding où tu empiles des burgers avec une vraie physique.",
            "Tu tiens le stand à burgers. Chaque client annonce un quota, et tu montes le burger pour l'atteindre, en direct, sur l'assiette. "
            f"Seul problème{NBSP}: les ingrédients obéissent à la <strong>physique</strong>. Viser la chute et garder la tour debout, c'est à toi de jouer. "
            f"Les ingrédients voisins déclenchent des effets en chaîne{NBSP}: plus la pile est haute et nette, plus le score grimpe.",
        ],
        flow_h="Déroulement d'une partie",
        steps=[
            (2, "Viser et lâcher", "Lâche les ingrédients de ta main sur l'assiette en visant, et déclenche des synergies entre voisins. Ils roulent, penchent et s'écroulent.",
             "Partie en cours : les ingrédients tombent sur l'assiette et s'empilent"),
            (3, "Coincer pour la synergie", "Pose le pain du dessus pour servir et être noté. Les effets des voisins s'enchaînent et le score s'envole. Quota manqué, c'est game over sur-le-champ.",
             "Écran de résultat d'un client"),
            (4, "Le food truck de nuit", f"Chaque client servi ouvre le food truck de nuit (la boutique){NBSP}: achète des caisses et des reliques, et jette les ingrédients inutiles. Satisfais le boss final pour l'emporter.",
             "Le food truck de nuit avec ses caisses et ses reliques"),
        ],
        feat_h="Ce que tu empiles",
        features=[
            ("Plus de 90 ingrédients", "Points, multiplicateurs, réceptacles. Chaque effet regarde le voisin"),
            ("Plus de 30 recettes", "La bonne combinaison donne un multiplicateur sur tout le burger et débloque de nouveaux ingrédients"),
            ("Plus de 40 reliques", "Effets permanents qui boostent des tags entiers"),
            ("8 chefs", "Pain signature et réserve de départ"),
            ("Des clients qui ont du caractère", "Préférences, dégoûts, os. La commande change à chaque fois"),
            ("Plus de 70 succès", "Avec un Codex et un Album de burgers"),
        ],
        challenge_h="Fais tes preuves",
        challenge="Le rang du resto ★0–5 et le Chef confirmé (le point de largage oscille tout seul) relèvent la difficulté. Les scores du défi du jour et des heures sup se disputent dans les classements Steam.",
        shots_h="Captures d'écran",
        shots=[
            (1, "Écran titre", "Écran titre d'Un pain au-dessus"),
            (2, "Empiler les ingrédients", "Empiler les ingrédients sur l'assiette"),
            (3, "Résultat", "Écran de résultat d'un client"),
            (4, "Le food truck de nuit", "Le food truck de nuit (boutique)"),
            (5, "Codex", "Codex des ingrédients"),
        ],
        info_h="Infos sur le jeu",
        facts=[
            ("Titre", "Un pain au-dessus"),
            ("Aussi connu sous", '<span lang="en">A Bun Above</span> / <span lang="ja">いただきバーガー</span>'),
            ("Genre", "Empilement physique × roguelike deckbuilding"),
            ("Développeur / éditeur", "NoZworks"),
            ("Plateforme", "PC (Steam) / Windows 10 et 11 (64 bits)"),
            ("Sortie", "4e trimestre 2026 (prévue)"),
            ("Langues", None),
        ],
        cta_text="Ajoute-le à ta liste de souhaits pour ne pas rater la sortie",
        cta_btn="Voir la page Steam",
        contact="Contact et presse",
        trademark="Steam est une marque commerciale ou une marque déposée de Valve Corporation.",
        font_label="Polices",
        lang_label="Langue",
    ),
    # ------------------------------------------------------------------ Español (neutro / LatAm)
    dict(
        dir="es/", hreflang="es", og_locale="es_LA", steam="latam", font="mplus",
        ss="es", ss_size=(1920, 1080), menu="Español",
        name="Burger a Tope",
        title="Burger a Tope – Roguelike de apilar hamburguesas | Steam",
        description="Burger a Tope (いただきバーガー) es un roguelike de apilar hamburguesas con física real. Suelta ingredientes, activa sinergias entre vecinos y mantén la torre en pie para cumplir la cuota de cada cliente. De NoZworks, llega a Steam en 2026.",
        og_title="Burger a Tope – Roguelike de apilar hamburguesas",
        og_description="Apila, no dejes que se caiga, y cobra por la sinergia. Agrégalo ya a tu lista de deseados en Steam.",
        ld_description="Roguelike de hamburguesas con física real: los ingredientes adyacentes encadenan efectos entre sí, y cuanto más alto y ordenado apilas, más sube la puntuación.",
        genres=["Roguelike", "Construcción de mazos", "Puzle de física", "Cocina"],
        os="Windows 10 / 11 (64 bits)",
        tagline="¡Suéltalo! ¡Apílalo! ¡Emparéjalo y que rinda!",
        subtitle="Roguelike de hamburguesas con física real",
        cta="Agregar a la lista de deseados en Steam",
        release="Lanzamiento previsto: 4.º trimestre de 2026 / Windows (Steam)",
        about_h="¿De qué va?",
        about=[
            "<strong>Burger a Tope</strong> es un roguelike de construcción de mazos en el que apilas hamburguesas con física real.",
            "Tú llevas la hamburguesería. Cada cliente pide una cuota, y tú montas la hamburguesa para cumplirla, en el momento, sobre el plato. "
            "El problema es que los ingredientes obedecen a la <strong>física</strong>. Apuntar la caída y mantener la torre en pie depende de ti. "
            "Los ingredientes adyacentes encadenan efectos entre sí: cuanto más alto y ordenado apilas, más sube la puntuación.",
        ],
        flow_h="Cómo va una partida",
        steps=[
            (2, "Apunta y suelta", "Suelta los ingredientes de tu mano sobre el plato apuntando bien y activa sinergias entre vecinos. Ruedan, se inclinan y se derrumban.",
             "Partida: los ingredientes caen sobre el plato y se apilan"),
            (3, "Empareja para la sinergia", "Corona con el bollo de arriba para servir y puntuar. Los efectos de los vecinos se encadenan y la puntuación se dispara. Si no llegas a la cuota, fin de la partida al instante.",
             "Pantalla de resultado de un cliente"),
            (4, "El food truck nocturno", "Al despachar a un cliente, abre el food truck nocturno (la tienda): compra cajas y reliquias y descarta los ingredientes que sobran. Deja satisfecho al jefe final y habrás ganado.",
             "El food truck nocturno con cajas y reliquias"),
        ],
        feat_h="Lo que apilas",
        features=[
            ("Más de 90 ingredientes", "Puntos, multiplicadores, cuencos. Todos los efectos miran al lado"),
            ("Más de 30 recetas", "La combinación justa da un multiplicador a toda la hamburguesa y desbloquea nuevos ingredientes"),
            ("Más de 40 reliquias", "Efectos permanentes que suben etiquetas enteras"),
            ("8 chefs", "Bollo propio y reserva inicial"),
            ("Clientes con personalidad", "Favoritos, manías, huesos. El pedido cambia cada vez"),
            ("Más de 70 logros", "Además, Compendio y Álbum de hamburguesas"),
        ],
        challenge_h="Ponte a prueba",
        challenge="El rango del local ★0–5 y el Chef veterano (el punto de caída se mueve solo de un lado a otro) suben la dificultad. Las puntuaciones del reto diario y de las horas extra compiten en las clasificaciones de Steam.",
        shots_h="Capturas de pantalla",
        shots=[
            (1, "Pantalla de título", "Pantalla de título de Burger a Tope"),
            (2, "Apilar ingredientes", "Apilar ingredientes sobre el plato"),
            (3, "Resultado", "Pantalla de resultado de un cliente"),
            (4, "El food truck nocturno", "El food truck nocturno (tienda)"),
            (5, "Compendio", "Compendio de ingredientes"),
        ],
        info_h="Información del juego",
        facts=[
            ("Título", "Burger a Tope"),
            ("También conocido como", '<span lang="en">A Bun Above</span> / <span lang="ja">いただきバーガー</span>'),
            ("Género", "Apilado con física × roguelike de construcción de mazos"),
            ("Desarrollador / editor", "NoZworks"),
            ("Plataforma", "PC (Steam) / Windows 10 y 11 (64 bits)"),
            ("Lanzamiento", "4.º trimestre de 2026 (previsto)"),
            ("Idiomas", None),
        ],
        cta_text="Agrégalo a tu lista de deseados y no te pierdas el lanzamiento",
        cta_btn="Ir a la página de Steam",
        contact="Contacto y prensa",
        trademark="Steam es una marca comercial o marca registrada de Valve Corporation.",
        font_label="Fuentes",
        lang_label="Idioma",
    ),
    # ------------------------------------------------------------------ Português (Brasil)
    dict(
        dir="pt-br/", hreflang="pt-BR", og_locale="pt_BR", steam="brazilian", font="mplus",
        ss="pt-br", ss_size=(1920, 1080), menu="Português (Brasil)",
        name="Pão nas Alturas",
        title="Pão nas Alturas – Roguelike de empilhar hambúrgueres | Steam",
        description="Pão nas Alturas (いただきバーガー) é um roguelike de empilhar hambúrgueres com física real. Solte ingredientes, ative sinergias entre vizinhos e mantenha a torre de pé para bater a meta de cada cliente. Da NoZworks, chega ao Steam em 2026.",
        og_title="Pão nas Alturas – Roguelike de empilhar hambúrgueres",
        og_description="Empilhe sem derrubar e lucre com a sinergia. Adicione já à sua lista de desejos no Steam.",
        ld_description="Um roguelike de hambúrgueres com física real: ingredientes vizinhos encadeiam efeitos entre si, e quanto mais alto e organizado for o seu empilhado, maior a pontuação.",
        genres=["Roguelike", "Construção de baralho", "Puzzle de física", "Culinária"],
        os="Windows 10 / 11 (64 bits)",
        tagline="Solte! Empilhe! Encaixe e faça sinergia!",
        subtitle="Um roguelike de hambúrgueres com física real",
        cta="Adicionar à lista de desejos no Steam",
        release="Lançamento previsto: 4º trimestre de 2026 / Windows (Steam)",
        about_h="Que jogo é esse?",
        about=[
            "<strong>Pão nas Alturas</strong> é um roguelike de construção de baralho em que você empilha hambúrgueres com física real.",
            "Você comanda a hamburgueria. Cada cliente traz uma meta, e você monta o hambúrguer para cumpri-la, na hora, direto no prato. "
            "O problema é que os ingredientes obedecem à <strong>física</strong>. Mirar a queda e manter a torre de pé é com você. "
            "Ingredientes vizinhos encadeiam efeitos entre si, e quanto mais alto e organizado for o seu empilhado, maior a pontuação.",
        ],
        flow_h="Como funciona uma partida",
        steps=[
            (2, "Mire e solte", "Solte os ingredientes da mão no prato com mira e ative sinergias entre vizinhos. Eles rolam, tombam e desmoronam.",
             "Partida: ingredientes caem no prato e são empilhados"),
            (3, "Encaixe e faça sinergia", "Coloque o pão de cima para servir e pontuar. Os efeitos dos vizinhos se encadeiam e a pontuação dispara. Não bateu a meta, é game over na hora.",
             "Tela de resultado de um cliente"),
            (4, "O food truck da noite", "Ao atender um cliente, o food truck da noite (a loja) abre: compre caixas e relíquias e descarte os ingredientes que não quer. Satisfaça o chefe final e a vitória é sua.",
             "O food truck da noite com caixas e relíquias"),
        ],
        feat_h="O que você empilha",
        features=[
            ("Mais de 90 ingredientes", "Pontos, multiplicadores, apoio. Todo efeito olha para o lado"),
            ("Mais de 30 receitas", "A combinação certa dá um multiplicador ao hambúrguer inteiro e desbloqueia novos ingredientes"),
            ("Mais de 40 relíquias", "Efeitos permanentes que elevam etiquetas inteiras"),
            ("8 chefs", "Pão exclusivo e estoque inicial"),
            ("Clientes com personalidade", "Preferências, restrições, ossos. O pedido muda a cada vez"),
            ("Mais de 70 conquistas", "Com Códice e Álbum de hambúrgueres"),
        ],
        challenge_h="Prove seu valor",
        challenge="O nível da loja ★0–5 e o Chef Veterano (o ponto de queda oscila sozinho de um lado a outro) aumentam a dificuldade. As pontuações do desafio diário e da Hora Extra disputam os rankings do Steam.",
        shots_h="Capturas de tela",
        shots=[
            (1, "Tela de título", "Tela de título de Pão nas Alturas"),
            (2, "Empilhando ingredientes", "Empilhando ingredientes no prato"),
            (3, "Resultado", "Tela de resultado de um cliente"),
            (4, "O food truck da noite", "O food truck da noite (loja)"),
            (5, "Códice", "Códice de ingredientes"),
        ],
        info_h="Informações do jogo",
        facts=[
            ("Título", "Pão nas Alturas"),
            ("Também conhecido como", '<span lang="en">A Bun Above</span> / <span lang="ja">いただきバーガー</span>'),
            ("Gênero", "Empilhamento com física × roguelike de construção de baralho"),
            ("Desenvolvedora / Publicadora", "NoZworks"),
            ("Plataforma", "PC (Steam) / Windows 10 e 11 (64 bits)"),
            ("Lançamento", "4º trimestre de 2026 (previsto)"),
            ("Idiomas", None),
        ],
        cta_text="Adicione à lista de desejos e não perca o lançamento",
        cta_btn="Ir para a página no Steam",
        contact="Contato e imprensa",
        trademark="Steam é uma marca comercial ou marca registrada da Valve Corporation.",
        font_label="Fontes",
        lang_label="Idioma",
    ),
    # ------------------------------------------------------------------ Русский
    dict(
        dir="ru/", hreflang="ru", og_locale="ru_RU", steam="russian", font="system",
        ss="ru", ss_size=(1920, 1080), menu="Русский",
        name="Булка Что Надо",
        title="Булка Что Надо — рогалик про башни из бургеров | Steam",
        description="«Булка Что Надо» (いただきバーガー) — рогалик, в котором вы складываете бургеры с настоящей физикой. Бросайте ингредиенты, запускайте синергии между соседями и держите башню, чтобы выполнить норму каждого клиента. От NoZworks, выходит в Steam в 2026 году.",
        og_title="Булка Что Надо — рогалик про башни из бургеров",
        og_description="Складывайте бургер, не роняйте его и собирайте комбо от соседних ингредиентов. Добавляйте в список желаемого в Steam.",
        ld_description="Физический рогалик про строительство бургеров: ингредиенты цепляют эффекты на соседей, и чем выше и аккуратнее башня, тем больше очков.",
        genres=["Рогалик", "Построение колоды", "Физическая головоломка", "Кулинария"],
        os="Windows 10 / 11 (64 бита)",
        tagline="Бросай! Складывай! Зажми ради синергии!",
        subtitle="Физический рогалик про строительство бургеров",
        cta="Добавить в желаемое в Steam",
        release="Выход — IV квартал 2026 г. / Windows (Steam)",
        about_h="Что это за игра?",
        about=[
            "<strong>«Булка Что Надо»</strong> — рогалик с построением колоды, в котором вы складываете бургеры с настоящей физикой.",
            "Вы управляете бургерной. Каждый клиент называет норму, а вы прямо на месте собираете бургер под неё. "
            "Проблема в том, что <strong>ингредиенты подчиняются физике</strong>. Прицелиться и не завалить башню — это только ваши руки. "
            "Ингредиенты цепляют эффекты на соседей: чем выше и аккуратнее башня, тем больше очков.",
        ],
        flow_h="Как проходит забег",
        steps=[
            (2, "Прицельтесь и бросайте", "Прицельно бросайте ингредиенты из руки на тарелку и запускайте синергии между соседями. Они катятся, кренятся и падают.",
             "Игровой процесс: ингредиенты падают на тарелку и складываются в башню"),
            (3, "Зажми ради синергии", "Накройте верхней булкой и подавайте — бургер оценят. Эффекты соседей складываются, и очки взлетают. Не дотянули до нормы — сразу конец игры.",
             "Экран результата клиента"),
            (4, "Ночной фудтрак", "После каждого клиента открывается ночной фудтрак (магазин): покупайте ящики и реликвии, выбрасывайте ненужные ингредиенты. Угодите последнему боссу — и победа ваша.",
             "Ночной фудтрак с ящиками и реликвиями"),
        ],
        feat_h="Что складываем",
        features=[
            ("Более 90 ингредиентов", "Очки, множители, ловушки для падений. Все эффекты смотрят на соседей"),
            ("Более 30 рецептов", "Нужная комбинация даёт множитель на весь бургер и открывает новые ингредиенты"),
            ("Более 40 реликвий", "Постоянные эффекты, усиливающие целый тег"),
            ("8 поваров", "У каждого свой уникальный бан и стартовая колода"),
            ("Клиенты с характером", "Любимое, нелюбимое, кости. Заказ меняется каждый раз"),
            ("Более 70 достижений", "А также Каталог и Альбом бургеров"),
        ],
        challenge_h="Проверьте мастерство",
        challenge="Ранг заведения ★0–5 и «Шеф-ветеран» (точка сброса сама ходит влево-вправо) поднимают сложность. Результаты ежедневного вызова и сверхурочных попадают в таблицы лидеров Steam.",
        shots_h="Скриншоты",
        shots=[
            (1, "Титульный экран", "Титульный экран «Булка Что Надо»"),
            (2, "Складываем ингредиенты", "Ингредиенты складываются на тарелке"),
            (3, "Результат", "Экран результата клиента"),
            (4, "Ночной фудтрак", "Ночной фудтрак (магазин)"),
            (5, "Каталог", "Каталог ингредиентов"),
        ],
        info_h="Об игре",
        facts=[
            ("Название", "Булка Что Надо"),
            ("Также известна как", '<span lang="en">A Bun Above</span> / <span lang="ja">いただきバーガー</span>'),
            ("Жанр", "Физическое строительство × рогалик с построением колоды"),
            ("Разработчик / издатель", "NoZworks"),
            ("Платформа", "PC (Steam) / Windows 10 и 11 (64 бита)"),
            ("Дата выхода", "IV квартал 2026 г. (планируется)"),
            ("Языки", None),
        ],
        cta_text="Добавьте в желаемое, чтобы не пропустить выход",
        cta_btn="Перейти на страницу в Steam",
        contact="Связь и пресса",
        trademark="Steam — товарный знак или зарегистрированный товарный знак Valve Corporation.",
        font_label="Шрифты",
        lang_label="Язык",
    ),
]
